const MESSAGES = {
  SUCCESS: 'Success!',
  UNKNOWN_AUTHOR: 'Unknown author',
  SOMETHING_WRONG: 'Something went wrong :(',
  SUCCESS_DELETED: 'Successfully deleted',
  UNKNOWN_BOOK: 'Unknown book',
  IS_YOUR_BOOK: 'We did not find your book, are you sure that its YOURS?',
  UNPUBLISH_BOOK_ERROR: 'Error deleting the book, try again later',
  ERROR_GETTING_BOOKS: 'Error getting books, try again later',
  NO_BOOK_STORAGE: 'There is no Book storage',
  USER_NAME_IN_USE: 'Username in use, choose another to continue.',
  USER_NOT_FOUND: 'User not found',
  USERNAME_PASSWORD_INCORRECT: 'Username or password incorrect',
  LOGIN_FAILED: 'Login failed, plase try again',
  UNAUTHORIZED: 'You are unauthorized >(',
  FIELDS_USERNAME_REQ: 'Username is required',
  FIELDS_PSEUDONYM_REQ: 'Pseudonym is required',
  FIELDS_PASSWORD_REQ: 'Password is required',
  FIELDS_PASSWORD_REGEX_MESSAGE: 'The password must have: 1 lowercase, 1 uppercase, 8 chars at least and 1 special char',
  FIELDS_TITLE_REQ: 'Title is required',
  FIELDS_DESCRIPTION_REQ: 'Description is required',
  FIELDS_COVER_REQ: 'Cover is required',
  FIELDS_PRICE_REQ: 'Price is required and must be numeric',
  AUTH_ENDPOINT_TEST: 'Auth works!',
  USER_ENDPOINT_TEST: 'User works!',
  BOOK_ENDPOINT_TEST: 'Book works!',
  ADMIN_ENDPOINT_TEST: 'Admin works!',
  BLOCKED_PUBLISHER_WARNING: 'Not so fast empire pal, you are not allowed to publish books in this store!',
  AUTHOR_ALREADY_BLOCKED: 'This author is already blocked and cant publish anything',
  YOU_CANT_DO_THIS: 'What are you doing?, you cant destroy yourself -_-',
};
module.exports = { MESSAGES };
